const LETTERS = [
	{
		title: "How my Dev Journey started",
		date: "Nov 15, 2019",
		time: "3 min",
		summary:
			"Hello! So I was thinking, what should be the central topic for my first medium article? I can say that with the exposure I have gotten recently, a lot really crossed my mind",
		tags: ["programming"],
		url: "https://medium.com/@obododavid5/how-my-dev-journey-started-247d65ec0a66",
		img: "https://miro.medium.com/max/1400/1*wxhoqvS8w9RYH0trt7Nc2g.jpeg",
		link: "1",
	},
	{
		title: "tch-a-5yrOld__MEMOIZATION",
		date: "May 29, 2020",
		time: "2 min",
		summary:
			"There lived a skilled carpenter named Evan Isaac, since time memorial there was nothing anyone asked him to make that he wasn’t capable of making",
		tags: ["programming"],
		url: "https://medium.com/@obododavid5/tch-a-5yrold-memoization-96dcaddaddcc",
		img: "https://miro.medium.com/max/1400/1*h1p71f7yFTzCatzzftF3yA.jpeg",
		link: "2",
	},
	{
		title: "Why did it End?",
		date: "Aug 3, 2020",
		time: "2 min",
		summary: `How does true love feel?
            How do butterflies in our stomach dance on seeing a soul?`,
		tags: ["life", "beingHuman", "love"],
		url: "https://medium.com/@obododavid5/why-did-it-end-eeba8dc6ff81",
		img: "https://miro.medium.com/max/1400/1*SCdiHoQf-CgFgAtpmYl3Cg.webp",
		link: "3",
	},
	{
		title: "My thoughts on curbing a horrible boss",
		date: "Mar 28, 2022",
		time: "2 min",
		summary: `Everyones talking about horrible bosses and their experience with them. I have had my own share of a horrible`,
		tags: ["workPlace", "lifeHack"],
		url: "https://medium.com/@obododavid5/my-thoughts-on-curbing-a-horrible-boss-153cd4ca5f7e",
		img: "https://miro.medium.com/max/1400/1*70OfxRwsr4sDwHCeQRYCNQ.jpeg",
		link: "4",
	},
	{
		title: "Journey to “portfolio version 3”",
		date: "May 27, 2022",
		time: "4 min",
		summary: `I have always known that documenting has a great impact. Ranging from documenting our sorrowful moments, happy moments, sad moments, joyful moments, and Im`,
		tags: ["consistency", "determination", "goal"],
		url: "https://medium.com/@obododavid5/journey-to-portfolio-version-3-ba31faf77c97",
		img: "https://miro.medium.com/max/1400/0*woSCdkovxNOq4Oqh",
		link: "5",
	},
	{
		title: "How to cancel an http/https request”",
		date: "Jun 18, 2022",
		time: "3 min",
		summary: `Recently had the need to cancel an http request and after googling a bit I did get the solution I needed. However, `,
		tags: ["programming", "http", "https", "ajax", "javascript", "cancel"],
		url: "https://obododavid.hashnode.dev/how-to-cancel-an-httphttps-request",
		img: "https://images.unsplash.com/photo-1593510987046-1f8fcfc512a0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2970&q=80",
		link: "6",
	},
	{
		title: "Testing Frontend Applications - Part 1: Introduction",
		date: "Oct 14, 2022",
		time: "5 min",
		summary: `Introduction to my series on testing frontend applications.`,
		tags: ["Testing", "React", "Next.js", "Frontend Development", "Testing Library"],
		url: "https://blog.davidobodo.com/testing-frontend-applications-introduction",
		img: "https://blog.davidobodo.com/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fres%2Fhashnode%2Fimage%2Fupload%2Fv1665787824519%2Ft8GFTtJwn.png%3Fw%3D1600%26h%3D840%26fit%3Dcrop%26crop%3Dentropy%26auto%3Dcompress%2Cformat%26format%3Dwebp&w=3840&q=75",
		link: "7",
	},
	{
		title: "Testing Frontend Applications - Part 2: Setting up Next.js project for testing",
		date: "Oct 17, 2022",
		time: "7 min",
		summary: `Setting up a Next.js appliaction for testing, since our application would be built with Next.js`,
		tags: ["React", "Next.js", "Testing Library", "Jest", "React Testing Library"],
		url: "https://blog.davidobodo.com/testing-frontend-applications-setting-up-nextjs-project-for-testing",
		img: "https://blog.davidobodo.com/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fres%2Fhashnode%2Fimage%2Fupload%2Fv1666014747608%2FBfe8-dIeL.png%3Fw%3D1600%26h%3D840%26fit%3Dcrop%26crop%3Dentropy%26auto%3Dcompress%2Cformat%26format%3Dwebp&w=3840&q=75",
		link: "8",
	},
	{
		title: "Testing Frontend Applications - Part 3A: What should I test?",
		date: "Oct 25, 2022",
		time: "7 min",
		summary: `Thought process behind deciding what to test in our application`,
		tags: ["React", "Next.js", "Testing Library", "Jest", "React Testing Library"],
		url: "https://blog.davidobodo.com/testing-frontend-applications-what-should-i-test",
		img: "https://blog.davidobodo.com/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fres%2Fhashnode%2Fimage%2Fupload%2Fv1666623487400%2FI8VYI-4JX.png%3Fw%3D1600%26h%3D840%26fit%3Dcrop%26crop%3Dentropy%26auto%3Dcompress%2Cformat%26format%3Dwebp&w=3840&q=75",
		link: "9",
	},
];

export default LETTERS;
