import Shared from "./shared";
import Pages from "./pages";

const {
	Projects,
	Footer,
	ScrollAlert,
	Banners,
	Nav,
	Radio,
	DarkRadialGradient,
	ModalWrapper,
	Layout,
	Noise,
	ProjectModal,
	Logo,
	Common,
	ScrollToTop,
	SectionPlaceholder,
	BannerCurtain,
	Spinner,
	AlternatingOpacity,
	ProgressBar,
	ProjectsViewSelector,
	Slider,
	ProjectsFilterModal,
	RouteTransitionOverlay,
	Preloader,
	PostCard,
	SeriesCard,
	Awwwards,
} = Shared;

const { HomePage, LettersPage, SingleProject, Blog } = Pages;
const { Thoughts, Work, Skills, FaintBgText, ProjectsHeading, Excellence } = HomePage;
const { SingleLetter } = LettersPage;
const {
	Highlight,
	CodeTitle,
	Center,
	MyInformation,
	SimilarArticles,
	ShareArticle,
	TopProgress,
	BlogView,
	ErrorBoundary,
} = Blog;

export {
	Thoughts,
	Banners,
	Layout,
	Work,
	Skills,
	FaintBgText,
	SingleLetter,
	ProjectsHeading,
	Excellence,
	SingleProject,
	Projects,
	Footer,
	ScrollAlert,
	Nav,
	Radio,
	DarkRadialGradient,
	ModalWrapper,
	Noise,
	ProjectModal,
	Logo,
	Common,
	ScrollToTop,
	SectionPlaceholder,
	BannerCurtain,
	Spinner,
	AlternatingOpacity,
	ProgressBar,
	ProjectsViewSelector,
	Slider,
	ProjectsFilterModal,
	RouteTransitionOverlay,
	Preloader,
	PostCard,
	SeriesCard,
	Highlight,
	CodeTitle,
	Center,
	SimilarArticles,
	MyInformation,
	ShareArticle,
	TopProgress,
	BlogView,
	ErrorBoundary,
	Awwwards,
};
