import Shared from "./shared";
import Pages from "./pages";

const {
	Projects,
	Contact,
	ScrollAlert,
	Banners,
	Nav,
	Radio,
	DarkRadialGradient,
	ModalWrapper,
	Layout,
	Noise,
	ProjectModal,
	Logo,
	Common,
	ScrollToTop,
	SectionPlaceholder,
	BannerCurtain,
	Spinner,
	AlternatingOpacity,
	ProgressBar,
	PageTransitionLayout,
	ProjectsViewSelector,
	Slider,
	ProjectsFilterModal,
	RouteTransitionOverlay,
	Preloader,
	HeadChildren,
} = Shared;

const { HomePage, LettersPage, SingleProject } = Pages;
const { Thoughts, Work, Skills, FaintBgText, ProjectsHeading, Excellence } = HomePage;
const { SingleLetter } = LettersPage;

export {
	Thoughts,
	Banners,
	Layout,
	Work,
	Skills,
	FaintBgText,
	SingleLetter,
	ProjectsHeading,
	Excellence,
	SingleProject,
	Projects,
	Contact,
	ScrollAlert,
	Nav,
	Radio,
	DarkRadialGradient,
	ModalWrapper,
	Noise,
	ProjectModal,
	Logo,
	Common,
	ScrollToTop,
	SectionPlaceholder,
	BannerCurtain,
	Spinner,
	AlternatingOpacity,
	ProgressBar,
	PageTransitionLayout,
	ProjectsViewSelector,
	Slider,
	ProjectsFilterModal,
	RouteTransitionOverlay,
	Preloader,
	HeadChildren,
};
